openapi: 3.0.3
info:
    title: Diary Service
    description: Service for Diary
    version: "1.0"
servers:
    - url: http://localhost:8000
paths:
    /signup:
        post:
            tags:
                - diary
            summary: UserSignup diary
            operationId: diary#UserSignup
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UserSignupRequestBody'
                        example:
                            email: Laudantium repellendus.
                            name: Aliquid doloribus.
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                type: string
                                format: binary
components:
    schemas:
        UserSignupRequestBody:
            type: object
            properties:
                email:
                    type: string
                    description: User email
                    example: Qui id hic vel est.
                name:
                    type: string
                    description: User name
                    example: Et repellendus ullam autem.
            example:
                email: Occaecati laboriosam molestiae necessitatibus nobis velit.
                name: Quia deleniti numquam vitae quaerat illo.
            required:
                - name
                - email
tags:
    - name: diary
